# Generated by Django 2.2.7 on 2019-12-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('cash_flow', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('confidence_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('time_interval', models.BooleanField()),
                ('billing_enable', models.BooleanField()),
                ('enable_error_name_payment', models.BooleanField()),
                ('files_format', models.CharField(max_length=10)),
            ],
        ),
    ]
