# Generated by Django 2.2.7 on 2019-12-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_package_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='is_acknowledged',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companies',
            name='cash_flow',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='companies',
            name='number_of_employees',
            field=models.BigIntegerField(),
        ),
    ]
